### ISSUE TITLE
Trouver une solution pour la congestion des queues

### ISSUE THREAD

**Issue by wpottier** [allprogrammic/resque#22]
Actuellement un worker cherche son prochain job dans la liste des queues par ordre alphabétique. La congestion d'une queue peut bloquer l'execution des taches d'une queues située après dans l'ordre alphabétique.

Exemple : 3 queues (A, B et C) avec 5000 taches chacunes.
 - Les workers vont d'abord traités toutes les taches de la queue A puis la B et enfin la C => les taches C auront beaucoup de retard.

Une amélioration pourrait être de faire en sorte que le choix des queue soit cyclique. Un worker prendrais un job A, puis un job B, puis un job C, puis un job A, etc (en sautant les queues vide).

Il pourrais être intéressant d'avoir les deux comportement de choix à disposition (le comportement actuel permettant de gérer une priorité des queues par ordre alphabétique)

**Comment by IrvinT** [comment]
@wpottier À fermer
